name: Rename Photo Files

on:
    push:
        branches: [main]

jobs:
    rename:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }} # Authenticate checkout with GitHub token

            - name: Check commit message
              id: check_commit
              run: |
                  COMMIT_MSG=$(git log -1 --pretty=%B)
                  if [[ ! "$COMMIT_MSG" =~ ^"🤖 Automated sync from NAS" ]]; then
                    echo "Commit message does not start with '🤖 Automated sync from NAS', skipping workflow."
                    echo "::set-output name=should_continue::false"
                    exit 0
                  fi
                  echo "::set-output name=should_continue::true"

            - name: Setup Node.js
              if: steps.check_commit.outputs.should_continue == 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies
              if: steps.check_commit.outputs.should_continue == 'true'
              run: |
                  npm init -y
                  npm install exifreader

            - name: Run rename script
              if: steps.check_commit.outputs.should_continue == 'true'
              run: node scripts/rename-photos.js src/assets/365/photos

            - name: Commit and push renamed files
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: steps.check_commit.outputs.should_continue == 'true'
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"
                  git add .
                  git commit -m "🤖 Renamed files with EXIF data" || echo "No changes to commit"
                  git push
